version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8-tut
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: php8-tut-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

  